# Note: configparser keys are case-insensitive, but values preserve case.

[System]
# Number of parallel patient folders to process simultaneously.
# CRITICAL: If using GPU Acceleration (CuPy), this dictates how many 
# matrices are loaded into VRAM. 
# For NumWorkers = 1, the system requires a 4–6 core CPU and a 4 GB GPU
NumWorkers = 1

[GLAM_Settings]
MaxRdfRadius = 100
AnisotropyCutoffRadius = 5
MaxLocalShellRadius = 30
NumRandomisations = 4
RdfSamplePoints = 1000

# QuantizationMethod can be "FixedCount" (for MRI) or "FixedWidth" (for CT)
QuantizationMethod = FixedCount

# --- FixedCount Parameters ---
NumGrayLevels = 24

# --- FixedWidth Parameters ---
BinWidth = 25
QuantizationMin = -100
QuantizationMax = 300

[File_Naming]
# Intencity normalization mask identifiers.
# Leave the NormMaskIdentifiers list [] empty to use 'MaskIdentifiers' for normalization.
NormMaskIdentifiers = ["_brain.nii.gz", "_skullstripped.nii.gz"]

# Segmentation file identifiers. 
MaskIdentifiers = ["_mask.nii.gz"]

SequenceIdentifiers = {
    "FLAIR": ["_flair", "-flair"],
    "T2": ["_t2", "-t2"],
    "T1": ["_t1", "-t1"],
    "T1CE": ["_t1ce", "-t1ce", "_t1gd", "-t1gd", "_t1c", "-t1c"]
    }

[Label_Mapping] 
# JSON keys need to be strings ("1", "99").
LabelMapping = {
    "3": "Enhancing_Tumor",
    "1": "Non_Enhancing_Tumor_Core",
    "2": "Peritumoral_Edema",
    "99": "Whole_Tumor"
    }

# Available habitats you can swap in:
# "1": "Enhancing_Tumor"
# "1+2": "Tumor_Core"
# "1+3": "Enhancing_and_Edema"
# "99": "Whole_Tumor"

LabelsForAnalysis = {
    "1+3": "Tumor_Core",
    "2+3": "Enhancing_and_Edema",
    "99": "Whole_Tumor"
    }

[Algorithm_Parameters]
SavgolWindow = 7
SavgolPoly = 3
PeakProminence = 4


###########################################################################
################## Feature Mapping Settings (very slow) ###################
###########################################################################

[Feature_Mapping]
# Set to "true" to enable the 3D map (niftii file) generation
EnableMapping = true

# The size (diameter) of the 3D sliding window in CM
MapWindowSizeCM = 1.5

# Minimum number of ROI voxels required within the window to perform a calculation
MapMinWindowVoxels = 200

# RDF parameters for the *local* calculation.
# Determines how far the physics interactions are measured within the window.
MapRDFMaxRadius = 20
# Increasing this reduces "shot noise" in the RDF calculation.
MapRDFSamplePoints = 100

# --- FEATURE LIST ---
# Copy/paste any of these names into the list below.
#
# === GLAM Features ===
# "CoordNum_Ln"
# "PotentialEnergy_Symlog"
# "StructuralPressureIndex_Symlog"
#
# === RDF Shape Features ===
# "RDF_PeakPosition"
# "LogRDF_Median"
# "LogRDF_Variance"
# "LogRDF_Skewness"
# "LogRDF_Kurtosis"
# "LogRDF_PeakHeight"
#

MapFeatures = ["StructuralPressureIndex_Symlog", "PotentialEnergy_Symlog", "Compressibility_Symlog", "ConfigurationalDisorderIndex", "LogRDF_Kurtosis", "LogRDF_Median", "LogRDF_Skewness"]

# How to reduce the N x N feature matrix to a single value for the map
# Options: "Mean", "Variance", "DiagMean", "OffDiagMean"
MapMetaMethod = ["Mean"]

# Set to true to save an additional 0-255 8-bit map for visualization
MapSaveVisualization = true